### ISSUE TITLE
AppModuleが存在しないエラー

### ISSUE THREAD

**Issue by sun3bow** [koriym/dii#6]
https://github.com/koriym/dii/blob/master/src/Dii.php#L49 から参照している`AppModule`がソースコード上に存在しないためエラーとなっております。

**エラーメッセージ**
`Class Koriym\Dii\Module\AppModule does not exist`

デモの方には同じネームスペースでクラスが存在しているので、こちらを`src/`配下に置く必要があると思われます。
https://github.com/koriym/dii/blob/master/demo/src/Module/AppModule.php

**Comment by koriym** [comment]
Diiを使うためにアプリケーション側で２つの名前空間を利用する設定です。

https://github.com/koriym/dii/tree/master/demo/src/Module
このように `AppModule` クラスとtmpフォルダを用意して、

https://github.com/koriym/dii/blob/master/demo/composer.json#L10
このようにcomposer.jsonでautoloadの設定を行えばいいかと思います。

`AppModule`は固定の名前空間をもつ起点のモジュールで、他のモジュールをインストールします。名前空間は固定でこのパッケージのものですが、アプリケーション側に設置して上記のcomposer.jsonのように名前空間をDiiのものに指定します。

**Comment by koriym** [comment]
READMEの

> Note: Module name is fixed as Koriym\Dii\Module\AppModule.

とあるようにAppModuleの名前は現在固定です。

**Comment by sun3bow** [comment]
なるほど、使い方の意図が理解できました。ありがとうございます！

**Comment by koriym** [comment]
AppModule, tmp の格納ディレクトリを`src-dii`などとして`composer.json`の`"autoload": {
 "psr-4":` で以下のように設定するのはどうでしょうか。

```
"Koriym\\Dii\\Module\\": "src-dii"
```
